name: Report email test

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

env:
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  DAILY_REPORT_FROM: ${{ secrets.DAILY_REPORT_FROM }}
  DAILY_REPORT_TO: ${{ secrets.DAILY_REPORT_TO }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: AlexisMateo/sendmail-action@5
        with:
          # smtp server
          smtp-server: 'smtp.gmail.com'
          # smtp server port
          smtp-server-port: 465
          # auth user
          auth-user:  jujuaditya037@gmail.com
          # auth password
          auth-password: Aditya@039
          # mail subject
          subject: message email check
          # The message to be sended
          body: 1234
          # where is the message from
          from: jujuaditya037@gmail.com
          # Who to send
          to: jujuaditya037@gmail.com
